italian_provinces = {
    "AG": {"City": "Agrigento", "Region": "Sicilia"},
    "AL": {"City": "Alessandria", "Region": "Piemonte"},
    "AN": {"City": "Ancona", "Region": "Marche"},
    "AO": {"City": "Aosta", "Region": "Valle d'Aosta"},
    "AR": {"City": "Arezzo", "Region": "Toscana"},
    "AP": {"City": "Ascoli Piceno", "Region": "Marche"},
    "AT": {"City": "Asti", "Region": "Piemonte"},
    "AV": {"City": "Avellino", "Region": "Campania"},
    "BA": {"City": "Bari", "Region": "Puglia"},
    "BL": {"City": "Belluno", "Region": "Veneto"},
    "BN": {"City": "Benevento", "Region": "Campania"},
    "BG": {"City": "Bergamo", "Region": "Lombardia"},
    "BI": {"City": "Biella", "Region": "Piemonte"},
    "BO": {"City": "Bologna", "Region": "Emilia-Romagna"},
    "BZ": {"City": "Bolzano", "Region": "Trentino-Alto Adige"},
    "BS": {"City": "Brescia", "Region": "Lombardia"},
    "BR": {"City": "Brindisi", "Region": "Puglia"},
    "BT": {"City": "Barletta-Andria-Trani", "Region": "Puglia"},
    "CA": {"City": "Cagliari", "Region": "Sardegna"},
    "CL": {"City": "Caltanissetta", "Region": "Sicilia"},
    "CB": {"City": "Campobasso", "Region": "Molise"},
    "CE": {"City": "Caserta", "Region": "Campania"},
    "CI": {"City": "Carbonia-Iglesias", "Region": "Sardegna"},
    "CT": {"City": "Catania", "Region": "Sicilia"},
    "CZ": {"City": "Catanzaro", "Region": "Calabria"},
    "CH": {"City": "Chieti", "Region": "Abruzzo"},
    "CO": {"City": "Como", "Region": "Lombardia"},
    "CS": {"City": "Cosenza", "Region": "Calabria"},
    "CR": {"City": "Cremona", "Region": "Lombardia"},
    "KR": {"City": "Crotone", "Region": "Calabria"},
    "CN": {"City": "Cuneo", "Region": "Piemonte"},
    "EN": {"City": "Enna", "Region": "Sicilia"},
    "FM": {"City": "Fermo", "Region": "Marche"},
    "FE": {"City": "Ferrara", "Region": "Emilia-Romagna"},
    "FI": {"City": "Firenze", "Region": "Toscana"},
    "FG": {"City": "Foggia", "Region": "Puglia"},
    "FC": {"City": "Forlì", "Region": "Emilia-Romagna"},
    "FO": {"City": "Forlì", "Region": "Emilia-Romagna"},
    "FR": {"City": "Frosinone", "Region": "Lazio"},
    "GE": {"City": "Genova", "Region": "Liguria"},
    "GO": {"City": "Gorizia", "Region": "Friuli Venezia Giulia"},
    "GR": {"City": "Grosseto", "Region": "Toscana"},
    "IM": {"City": "Imperia", "Region": "Liguria"},
    "IS": {"City": "Isernia", "Region": "Molise"},
    "SP": {"City": "La Spezia", "Region": "Liguria"},
    "AQ": {"City": "L'Aquila", "Region": "Abruzzo"},
    "LT": {"City": "Latina", "Region": "Lazio"},
    "LE": {"City": "Lecce", "Region": "Puglia"},
    "LC": {"City": "Lecco", "Region": "Lombardia"},
    "LI": {"City": "Livorno", "Region": "Toscana"},
    "LO": {"City": "Lodi", "Region": "Lombardia"},
    "LU": {"City": "Lucca", "Region": "Toscana"},
    "MC": {"City": "Macerata", "Region": "Marche"},
    "MN": {"City": "Mantova", "Region": "Lombardia"},
    "MS": {"City": "Massa", "Region": "Toscana"},
    "MT": {"City": "Matera", "Region": "Basilicata"},
    "ME": {"City": "Messina", "Region": "Sicilia"},
    "MI": {"City": "Milano", "Region": "Lombardia"},
    "MO": {"City": "Modena", "Region": "Emilia-Romagna"},
    "MB": {"City": "Monza", "Region": "Lombardia"},
    "NA": {"City": "Napoli", "Region": "Campania"},
    "NO": {"City": "Novara", "Region": "Piemonte"},
    "NU": {"City": "Nuoro", "Region": "Sardegna"},
    "OG": {"City": "Ogliastra", "Region": "Sardegna"},
    "OT": {"City": "Olbia", "Region": "Sardegna"},
    "OR": {"City": "Oristano", "Region": "Sardegna"},
    "PD": {"City": "Padova", "Region": "Veneto"},
    "PA": {"City": "Palermo", "Region": "Sicilia"},
    "PR": {"City": "Parma", "Region": "Emilia-Romagna"},
    "PV": {"City": "Pavia", "Region": "Lombardia"},
    "PG": {"City": "Perugia", "Region": "Umbria"},
    "PU": {"City": "Pesaro", "Region": "Marche"},
    "PE": {"City": "Pescara", "Region": "Abruzzo"},
    "PC": {"City": "Piacenza", "Region": "Emilia-Romagna"},
    "PI": {"City": "Pisa", "Region": "Toscana"},
    "PT": {"City": "Pistoia", "Region": "Toscana"},
    "PN": {"City": "Pordenone", "Region": "Friuli Venezia Giulia"},
    "PZ": {"City": "Potenza", "Region": "Basilicata"},
    "PO": {"City": "Prato", "Region": "Toscana"},
    "PS": {"City": "Pesaro", "Region": "Marche"},
    "RG": {"City": "Ragusa", "Region": "Sicilia"},
    "RA": {"City": "Ravenna", "Region": "Emilia-Romagna"},
    "RC": {"City": "Reggio Calabria", "Region": "Calabria"},
    "RE": {"City": "Reggio Emilia", "Region": "Emilia-Romagna"},
    "RI": {"City": "Rieti", "Region": "Lazio"},
    "RM": {"City": "Roma", "Region": "Lazio"},
    "RN": {"City": "Rimini", "Region": "Emilia-Romagna"},
    "RO": {"City": "Rovigo", "Region": "Veneto"},
    "SA": {"City": "Salerno", "Region": "Campania"},
    "SS": {"City": "Sassari", "Region": "Sardegna"},
    "SV": {"City": "Savona", "Region": "Liguria"},
    "SI": {"City": "Siena", "Region": "Toscana"},
    "SU": {"City": "Sud Sardegna", "Region": "Sardegna"},
    "SR": {"City": "Siracusa", "Region": "Sicilia"},
    "SO": {"City": "Sondrio", "Region": "Lombardia"},
    "TA": {"City": "Taranto", "Region": "Puglia"},
    "TI": {"City": "Ticino", "Region": "Switzerland"},
    "TE": {"City": "Teramo", "Region": "Abruzzo"},
    "TR": {"City": "Terni", "Region": "Umbria"},
    "TO": {"City": "Torino", "Region": "Piemonte"},
    "TP": {"City": "Trapani", "Region": "Sicilia"},
    "TN": {"City": "Trento", "Region": "Trentino-Alto Adige"},
    "TV": {"City": "Treviso", "Region": "Veneto"},
    "TS": {"City": "Trieste", "Region": "Friuli Venezia Giulia"},
    "UD": {"City": "Udine", "Region": "Friuli Venezia Giulia"},
    "VA": {"City": "Varese", "Region": "Lombardia"},
    "VE": {"City": "Venezia", "Region": "Veneto"},
    "VB": {"City": "Verbania", "Region": "Piemonte"},
    "VC": {"City": "Vercelli", "Region": "Piemonte"},
    "VR": {"City": "Verona", "Region": "Veneto"},
    "VV": {"City": "Vibo Valentia", "Region": "Calabria"},
    "VI": {"City": "Vicenza", "Region": "Veneto"},
    "VT": {"City": "Viterbo", "Region": "Lazio"}
}